In [100]:
import pandas as pd
import numpy as np
import tqdm
import sys
import matplotlib.pyplot as plt
sys.path.append('../../')

In [4]:
from src.utils.error_utils import high_vel_nan, lowess_fill, graph_locations, get_nan_prec, nan_good, load_file

In [145]:
df = pd.read_csv('dyed_preds_df.csv')
df = df[(df['single/multi'] == 'multi') & (df['pred'] == True) & (df['initial nan'] < 0.05)]

In [146]:
df.shape

(56, 15)

In [147]:
def get_max_vel(locations, node):
    x = np.sqrt(np.sum(np.square(locations[:-1, node, :, :] - locations[1:, node, :, :]), axis=1))
    mean, std = np.nanmean(x, axis=0), np.nanstd(x, axis=0)
    high, low = mean + (3 * std), mean - (3 * std)   
    return mean, std, high
    

In [148]:
means = np.zeros((df.shape[0] * 2, 5))
stds = np.zeros((df.shape[0] * 2, 5))
highs = np.zeros((df.shape[0] * 2, 5))

In [149]:
count = 0
for index, row in tqdm.tqdm(df.iterrows()):
    locations = load_file(row)
    for node in range(locations.shape[1]):
        mean, std, high = get_max_vel(locations, node)
        means[count:count+2, node] = mean
        stds[count:count+2, node] = std
        highs[count:count+2, node] = high
    count += 2

56it [00:01, 41.82it/s]


In [150]:
print(np.mean(means, axis=0))

[10.41527502  9.02789887  9.07646772  8.81392692  8.07691618]


In [151]:
print(np.median(highs, axis=0))

[64.7808995  59.06738033 60.24554831 58.16596389 60.50940762]


In [157]:
np.sort(highs, axis=0)[-3:]

array([[ 168.77012265,  146.34355062,  148.57678779,  147.52182395,
         210.26570079],
       [ 381.38805391,  311.97767461,  153.61570874,  150.55935301,
         236.2906489 ],
       [2331.37340135,  595.30834742, 1461.60640204,  343.04576626,
         280.90042038]])

In [ ]:
# number of vids * 2 , nodes 
# mean, std, high, low